#!/bin/bash

# Load config values:
if [ -e manage.conf ]; then
    source manage.conf
else
    # Defaults
    TOOLPATH="tools"
    ENVPATH="env/"
    PYLIBDIR="lib/py"
    CLEANPTTRNS=(
        "*~"
        "*swp"
        "*.pyc"
    )
fi

function sysmsg() {
    now=$(date "+%I:%m %p")
    echo "${now}  " $@
}

function setup_appengine_env() {
    appenginepath=$1
    if [ -L ${ENVPATH}/google_appengine ]; then
        sysmsg "Removing existing symlink"
        rm ${ENVPATH}/google_appengine
    else
        sysmsg "Appengine symlink does not exist"
    fi

    if [ -z ${appenginepath} ]; then
        sysmsg "Enter path to appengine installation"
        read appenginepath
        echo "AppEngine path: ${appenginepath}"
    fi

    if [ -e ${appenginepath} ] && [ -e ${appenginepath}/appcfg.py ]; then
        sysmsg "Setting up appengine"
        ln -s ${appenginepath} ${ENVPATH}/google_appengine
    else
        sysmsg "Invalid AppEngine installation path"
    fi
}
function setup_paths() {
    sysmsg "Fixing import paths in manage.py"
    function a() { echo "$1" >> tmpmanage.py; }
    a "#!/usr/bin/env python2"
    head manage.py -n 3 | tail -n 2 >> tmpmanage.py
    a "from os.path import normpath, join, dirname, abspath"
    a "sys.path.insert(0, normpath(join(dirname(abspath(__file__)),'lib/py')))"
    tail -n +4 manage.py >> tmpmanage.py
    mv tmpmanage.py manage.py
    chmod a+x manage.py
}
function setup_urls() {
    sysmsg "Setting up urls in app.yaml"
    sysmsg "  - To finish setting up, please set those values in settings.py:"
    sysmsg "    STATIC_ROOT='static/files'"
    sysmsg "    STATIC_URL='/static/'"
    head app.yaml -n -2 > tmpapp.yaml
    echo "- url: /static" >> tmpapp.yaml
    echo "  static_dir: /static_files" >> tmpapp.yaml
    echo "" >> tmpapp.yaml
    tail app.yaml -n 2 >> tmpapp.yaml
    mv tmpapp.yaml app.yaml
}
function cmd_download_deps() {
    tmpdir="tmpinstalls"
    github="https://github.com/django-nonrel"
    zips=(
        "${github}/django/archive/nonrel-1.5.zip"
        "${github}/djangoappengine/archive/master.zip"
        "${github}/djangotoolbox/archive/master.zip"
        "${github}/django-dbindexer/archive/master.zip"
        "https://bitbucket.org/twanschik/django-autoload/get/tip.zip"
    )
    nonrel_deps=(
        'djangoappengine'
        'django'
        'djangotoolbox'
        'dbindexer'
        'autoload'
    )

    sysmsg "Creating temporary directory ${tmpdir}"
    mkdir "${tmpdir}"

    sysmsg "Creating libs directory ${PYLIBDIR}"
    mkdir -p "${PYLIBDIR}"

    cd ${tmpdir}

    # Extract the zipfiles
    sysmsg "Downloading dependencies required to run on appengine"
    for url in "${zips[@]}"; do
        fname=$(basename ${url})

        sysmsg "  - Downloading ${fname} from ${url}"
        wget -q ${url}

        sysmsg "    Unpacking ${fname}"
        unzip -q ${fname}

        sysmsg "    Removing ${fname}"
        rm ${fname}
    done

    # Copy python libraries
    sysmsg "Installing libraries to '${PYLIBDIR}'"
    for dep in "${nonrel_deps[@]}"; do
        libdir="$(find -mindepth 2 -maxdepth 2 -name ${dep} -type d)"
        sysmsg "  - ${libdir} -> ${PYLIBDIR}/$(basename ${libdir})"
        cp -r "${libdir}" "../${PYLIBDIR}/"
    done

    sysmsg "Removing directory ${tmpdir}"
    cd ..
    rm -rf ${tmpdir}
}
function cmd_setupproject() {
    project=$1
    appenginepath=$2
    function a() { echo "$1" >> fixpath.py; }
    echo '# -*- coding: utf-8 -*-' > fixpath.py
    a 'import sys'
    a 'from os.path import normpath, join, dirname, abspath'
    a 'sys.path.insert(0, normpath(join(dirname(abspath(__file__)), "lib/py")))'
    a 'from djangoappengine.main import application as main'
    a 'from djangoappengine.appstats import application as appstats'

    sysmsg "Creating django project '${project}'"
    djangobin="${PYLIBDIR}/django/bin"
    export DJANGO_SETTINGS_MODULE=""
    export PYTHONPATH=".:${PYLIBDIR}"
    echo "DJANGOBIN: ${djangobin}"
    python2 ${djangobin}/django-admin.py startproject                   \
              --name=app.yaml                                           \
              --template=lib/py/djangoappengine/conf/project_template   \
              ${project} .

    #setup_paths
    virtualenv ${ENVPATH} --no-site-packages
    setup_appengine_env ${appenginepath}
    setup_urls
}
function cmd_createproject() {
    sysmsg "Initializing the project"

    if [ $# -lt 2 ]; then
        echo "USAGE: $0 createproject PROJECT_NAME APPENGINE_PATH"
        exit -2
    fi

    project=$1

    # Remove existing .git dir
    if [ -e .git ]; then
        sysmsg "Removing existing .git directory"
        rm -rf .git
    fi

    # create nested project directory
    mkdir -p "${project}"
    mv "manage" "${project}/."

    # create a git repository
    git init
    # and do the first commit
    git add README.md LICENSE .gitignore "${project}/manage"
    git commit -m 'Initial commit'

    # change to the nested folder before continuing
    cd "${project}"

    cmd_download_deps
    cmd_setupproject $@

    git add .
    git commit -m 'Generated project files'
}
function cmd_clean() {
    sysmsg 'Cleaning '"${pttrn}"
    for pttrn in "${CLEANPTTRNS[@]}"; do
        rm -rf $(find -iname "${pttrn}")
    done
}
function cmd_deploy() {
  sysmsg "Uploading the app to the server"
  ./manage.py deploy
}
function cmd_install_pylib() {
    libname=$1
    [[ $# > 1 ]] && libdir=$2 || libdir=$1
    sysmsg "Installing ${libname} to ${libdir}"
    source ${ENVPATH}/bin/activate
    pip2 install ${libname}
    sysmsg "Copying ${libdir} to ${PYLIBDIR}/"
    cp -r ${ENVPATH}/lib/python2.7/site-packages/${libdir} ${PYLIBDIR}/${libdir}
}


export PATH="$(pwd)/${ENVPATH}/google_appengine:$PATH"
export PYTHONPATH=${PYLIBDIR}
export DJANGO_SETTINGS_MODULE="settings"


# Extract cmline args:
cmd=$1
shift 1

case "${cmd}" in
'downloaddeps')     cmd_download_deps $@ ;;
'setupproject')     cmd_setupproject $@ ;;
'createproject')    cmd_createproject $@ ;;
'deploy')           cmd_deploy ;;
'pylib')            cmd_install_pylib $@ ;;
'runtool')
    tool=$1
    shift 1
    PYTHONPATH=".:lib/py" ./${TOOLPATH}/${tool}.py $@
    ;;
*)
    ./manage.py ${cmd} $@
    ;;
esac
